# Generated by Django 5.1.1 on 2024-09-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
